### ISSUE TITLE
Omer Zachar

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#1]
https://omerzachar.github.io/OZ-demo.github.io/

https://github.com/OmerZachar/OZ-demo.github.io

**Comment by szabgab** [comment]
The website should be at https://omerzachar.github.io/ for this yo need to rename your repo to be omerzachar.github.io

**Comment by szabgab** [comment]
Once you made the changes and you are done, please comment here so I'll know to check.

**Comment by OmerZachar** [comment]
website - https://omerzachar.github.io/
profile - https://github.com/OmerZachar/omerzachar.github.io

**Comment by szabgab** [comment]
Accepted, but please add some more content and make it look nicer.
