### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by liroh99** [szabgab/wis-python-course-2024-04#106]
Submitting assignment 4. 
https://github.com/liroh99/Assignments/tree/main/day04
Is there some issue in my 3rd assignment because I see you haven't commented on it. 
Thanks, 
Liron

**Comment by szabgab** [comment]
I commented on #84 about 40 minutes ago.

**Comment by szabgab** [comment]
nice, after reading in the whole content of the file you can outdent the rest of the code by one level. Those lines don't need to be inside the `with` statement`
