### ISSUE TITLE
day05 - assignment - Thay Karmin

### ISSUE THREAD

**Issue by THAYKARMIN** [szabgab/wis-python-course-2024-04#116]
https://github.com/THAYKARMIN/assignments/tree/main/day05

**Comment by szabgab** [comment]
The file is called `.gitignore`  (with an `e` at the end) and it is always in the root of the repository not in a subfolder.

Nice use of a fixture in the test.
There is no point in `parametrize` if you only have one test case and now the input and the expected result seem disconnected as they come from different places.
