### ISSUE TITLE
Day 05 part 2 timestamps

### ISSUE THREAD

**Issue by YuvalBernard** [szabgab/wis-python-course-2024-04#119]
00:00 - Introduction to code quality assurance.
10:30 - Intentional bug in custom library; writing a testing program to check for bugs. 
12:25 - `pytest` package: installation and using `pytest.assert`.
18:40 - Interpreting a test report.
19:50 - Student question: correctly using the `pytest` package.
22:55 - Student discussion: multiple `pytest.assert` calls in a single testing function.
29:30 - Asserting multiple cases in conjunction with `@pytest.mark.parametrize`
37:50 - Running a specific test within a whole testing program.
39:57: Further motivation for writing tests for code.

**Comment by szabgab** [comment]
thanks
