### ISSUE TITLE
Day05 HW solution - Yuval Bernard

### ISSUE THREAD

**Issue by YuvalBernard** [szabgab/wis-python-course-2024-04#120]
https://github.com/YuvalBernard/weizmann-python-assignments/tree/master/day05

**Comment by szabgab** [comment]
Looks good, but the `def print_file_characteristics(filename):` should really only contain the printing. all the rest should be in a separate function in the helper file. That function would get the name of the file and return the 3 values. `n_lines`, `n_words`, `n_characters`.

In the tests you could move all the test-cases into a single data-structure and use that for the parameters. That would allow you to eliminate the repetition of the input data.
