### ISSUE TITLE
HW day05 - Mazal Faraj

### ISSUE THREAD

**Issue by Mazalik** [szabgab/wis-python-course-2024-04#126]
Hi,

https://github.com/Mazalik/python_course_sol/tree/main/day05

thank you!
Mazal

**Comment by szabgab** [comment]
looks good. just one note: usually we use filename all lower case and if they consist of multiple words then we put underscore between them: e.g. functions_count_from_text.py

**Comment by szabgab** [comment]
Oh and you too (as several other students) are missing the `.gitignore` file and this `__pycache__` can be seen when we run `git status`. Please add the `.gitignore` file (see one of the earlier videos
