### ISSUE TITLE
day05 - Shahar Garin

### ISSUE THREAD

**Issue by ShaharGarin** [szabgab/wis-python-course-2024-04#128]
My assignment can be found [here](https://github.com/ShaharGarin/shahar_assignments/tree/main/day05). Thank you.

**Comment by szabgab** [comment]
There is a file called `countfunctions` in the repository without the `.py` extension. The tests are failing:

```
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0
rootdir: /home/gabor/Weizmann/Shahar-Garin/day05
plugins: anyio-4.3.0
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
___________________ ERROR collecting test_countfunctions.py ____________________
ImportError while importing test module '/home/gabor/Weizmann/Shahar-Garin/day05/test_countfunctions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_countfunctions.py:1: in <module>
    import countfunctions as cf
E   ModuleNotFoundError: No module named 'countfunctions'
=========================== short test summary info ============================
ERROR test_countfunctions.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.09s ===============================
```

**Comment by szabgab** [comment]
Also there is no `.gitignore` file in your repository and this we can see the `__pycache__` folder.

It seems you are not using the git client to add file, but you upload them via the web interface. You need to learn to use the git client. Ask the other students for help, if you need it.

**Comment by ShaharGarin** [comment]
> There is a file called `countfunctions` in the repository without the `.py` extension. The tests are failing:
> 
> ```
> ============================= test session starts ==============================
> platform linux -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0
> rootdir: /home/gabor/Weizmann/Shahar-Garin/day05
> plugins: anyio-4.3.0
> collected 0 items / 1 error                                                    
> 
> ==================================== ERRORS ====================================
> ___________________ ERROR collecting test_countfunctions.py ____________________
> ImportError while importing test module '/home/gabor/Weizmann/Shahar-Garin/day05/test_countfunctions.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib/python3.12/importlib/__init__.py:90: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> test_countfunctions.py:1: in <module>
>     import countfunctions as cf
> E   ModuleNotFoundError: No module named 'countfunctions'
> =========================== short test summary info ============================
> ERROR test_countfunctions.py
> !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
> =============================== 1 error in 0.09s ===============================
> ```

Fixed.

Regarding the git client: It's just more comfortable for me to work through the web interface. Is that an issue? If so, I can try and get used to using the git client again.

**Comment by szabgab** [comment]
There is still no .gitignore file
You would not get issues like wrong filename if you used the git client.  The real value I am trying to teach is the use of the local git (command line or in VS Code). Pushing out to github is only to share the files with me.  Once you practice a bit it will be a lot easier than the web interface.

**Comment by ShaharGarin** [comment]
> There is still no .gitignore file You would not get issues like wrong filename if you used the git client. The real value I am trying to teach is the use of the local git (command line or in VS Code). Pushing out to github is only to share the files with me. Once you practice a bit it will be a lot easier than the web interface.

I've added the .gitignore file.

**Comment by szabgab** [comment]
ok
