### ISSUE TITLE
Help with day05

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#129]
I Gabor, I'm really struggling with the homework and don't know how to address the code each time. i still didn't understand at all what sys does and I don't understand how I need to build the code.

**Comment by szabgab** [comment]
You already used `sys` in the 4th assignment. It does not `do` anything. It is a module that has attributes. The one we used is called `argv`.

* You could ask chatgpt or one of the class-mates to explain to you.
* You can can take a step back and watch the videos of the [earlier recording](https://code-maven.com/programming-bootcamp-for-scientists) that might help.
* You can go over the slides and the [exercises](https://code-maven.com/slides/python/toc), those help you practice more basic things.

**Comment by OmerZachar** [comment]
Ok, i'll try to do that. I would please need an extension for submitting the assignment for Day05 please, because it will take me more time to figure it out.

**Comment by szabgab** [comment]
Sure, you can get a few extra days. Let me know how you progress. If there are other exercises you solve and you'd like to get feedback on them, add them also to git in some folder and comment here.

**Comment by OmerZachar** [comment]
Hi Gabor,

with the help of students and no night sleep I managed to finish the Day05 assignment!
https://github.com/OmerZachar/projects/tree/main/Day05

**Comment by szabgab** [comment]
Nice, but there are a number of issues:

* The name of the test file must start with `test_` in order for `pytest` to find it.
* the test is looking for a file called `File1.txt` but the file is incorrectly called `File1.py` meaning the tests now fail.

Please fix these.

**Comment by szabgab** [comment]
Also because you don't have a `.gitignore` file the generated `__pycache__` folder can be seen when you run `git status`. Please add the `.gitignore` file. We discussed this in one of the earlier videos.

**Comment by OmerZachar** [comment]
Hi Gabor, I corrected the code after your notes.

**Comment by szabgab** [comment]
The text files are still called `.py` which is going to be really confusing as they are text files and not Python programs.

Also the tests fail

```
FAILED test_function.py::test_count_char - assert 1034 == 1028
FAILED test_function.py::test_count_lines - assert 253 == 181
```

This is probably due to the fact that Linux and Windows handle newlines differently.
