### ISSUE TITLE
day05 assignment - Shaked Levy

### ISSUE THREAD

**Issue by LevyShaked** [szabgab/wis-python-course-2024-04#132]
https://github.com/LevyShaked/Assignments_rep/tree/main/day05

**Comment by szabgab** [comment]
* Filenames are usually all lowercase.
* Specifically you called the test file `TEST_A5_BUS_LOG.py` but Linux is case sensitive and `pytest` is looking for files with name starting with `test_` in lower-case, so pytest does not see this test file.
* If you put variables in the body of the test file those should be constants and thus we usually write those in all upper case letters

* I could run the test as `pytest TEST_A5_BUS_LOG.py`  but you should rename the file to be all lower case letters.
