### ISSUE TITLE
Exercise 5 - Hernan Rubinstein

### ISSUE THREAD

**Issue by hernanRubinstein** [szabgab/wis-python-course-2024-04#134]
https://github.com/hernanRubinstein/Solutions_Python_BC/tree/main/Day05

main functions in [char_count_pack.py]
test file in [test_char_count.py]

* NOTE: I changed the essentials of my 'program' for the purpose of this exercise

**Comment by szabgab** [comment]
the `__pycache__` folder is now in git. It should be removed and github needs to be told to ignore that folder. See earlier videos and the email I sent a couple of days ago.

The solution looks good, but the fact that you had to comment out the calling of `main` indicates that this is not a good solution. The functions that you test should be in a separate file (as we learned) or you can use `__main__` as at least one other student did (despite that we did not learn about it)

**Comment by szabgab** [comment]
The content of .gitignore has a typo now, please fix.
