### ISSUE TITLE
Assingment Day05 -Adi Bar-El Meisel

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#137]
Hi,
Please see attached my solution to Day05.
[https://github.com/AdiBarelMeisel/Assignments/tree/main/Day05](url)

Adi

**Comment by szabgab** [comment]
* In the test file there is no need for calling the test functions, the last 5 lines are unnecessary and confusing
* The  `__pycache__` folder should be removed from git and it should be ignored by git.

**Comment by AdiBarelMeisel** [comment]
Hi @szabgab,

Took care of both issues :)
[https://github.com/AdiBarelMeisel/Assignments/tree/main/Day05](https://github.com/AdiBarelMeisel/Assignments/tree/main/Day05)

**Comment by szabgab** [comment]
The test looks good now, but there is still no `.gitignore` file. Please add it.

**Comment by AdiBarelMeisel** [comment]
fixed :)
@szabgab

**Comment by szabgab** [comment]
... that should also include `__pycache__`

**Comment by AdiBarelMeisel** [comment]
My bad, I forgot to save the file before I commit it to Git.
Now it is fixed.
Thanks :)
@szabgab

**Comment by szabgab** [comment]
It should be ` __pycache__` not `/Day05/__pycache__`

**Comment by AdiBarelMeisel** [comment]
Hey,
Moved git ignore to Day05 folder and updated path accordingly.
Adi
@szabgab

**Comment by szabgab** [comment]
Where did you get this idea? `.gitignore` needs to be in the root of the whole repository. It was in the right place. Just its content was not correct.

**Comment by AdiBarelMeisel** [comment]
Hi,
In the first place, I understood that the `.gitignore` file should be in the root directory, but since the `__pycache__` directory was inside the `Day05` directory, I only assumed that the entire path should be added - saw on a few online guides that this was the convention.
When you requested I fix the path to the `__pycache__` only, I simply assumed that you expected the `.gitignore` file to be in the local folder, but apparently I understood you incorrectly.
Fixed it accordingly now.

Adi
@szabgab

**Comment by szabgab** [comment]
OK
