### ISSUE TITLE
Day6 Avital Rosner

### ISSUE THREAD

**Issue by Avitalrosner** [szabgab/wis-python-course-2024-04#141]
Good evening,

Here is my 6th assignment:

https://github.com/Avitalrosner/Python_course_Assignments/tree/main/Day6

Thank you,

Avital

**Comment by szabgab** [comment]
I can't run the test as it references `'C:/python/Python_course_Assignments/Day6/test_umi.csv'` I don't have that path.
The file is in the same folder as the test so the code should only include the name of the file `'test_umi.csv'`

**Comment by Avitalrosner** [comment]
Thank you for bringing that to my attention,
Should be fine now :)

**Comment by szabgab** [comment]
now looks ok
