### ISSUE TITLE
day06 - Shahar Garin

### ISSUE THREAD

**Issue by ShaharGarin** [szabgab/wis-python-course-2024-04#143]
Hello,

[The 6th assignment](https://github.com/ShaharGarin/shahar_assignments/tree/main/day06) is ready. Hopefully it's scale is sufficient.

**Comment by szabgab** [comment]
Please do not copy functions for testing.

**Comment by ShaharGarin** [comment]
> Please do not copy functions for testing.

I understand why it's not ideal, but the full code prompts the user for inputs (in the form of a browser window and in the form of regular inputs) and it initiates these prompts for the test as well (despite the tested functions not having any prompts in them).
We've discussed it over email, and you said it would be ok for this assignment (unless I misunderstood your replies?).

**Comment by ShaharGarin** [comment]
> Please do not copy functions for testing.

I've corrected it, as you've suggested. The mathematical function I'm testing are now in a separate file, and that file is imported by the main program. The same file used in the code is now the file that is being tested.

**Comment by szabgab** [comment]
Looks much better now.
