### ISSUE TITLE
boyue Day6

### ISSUE THREAD

**Issue by DahaiSun** [szabgab/wis-python-course-2024-04#147]
https://github.com/DahaiSun/wis_python_course_assignments/tree/main/day6

**Comment by szabgab** [comment]
This line `file_path = r'E:\github\wis_python_course_assignments\day6\StatisticsQ1.xlsx'` makes it imposssible for anyone except you to use the program. The program should get the name of the file from the command line.

FYI "start excel" is a Windows command it won't work on Linux and macOS

This line ` data = load_data(r'E:\github\wis_python_course_assignments\day6\StatisticsQ1.xlsx', 'Sheet1')` in the test
makes it impossible for me to run the tests.

**Comment by DahaiSun** [comment]
Hi Gabor, thanks for the detailed suggestions,

I have updated the data_distribution.py:
1） romoved the file path, changed it to comannd required way.
usage:
python3 data_distribution.py <file_path> <sheet_name>" 
in my case the command should be：python3 data_distribution.py StatisticsQ1.xlsx Sheet1

2）for the "start excel", the program will check working system. open the output file when using windows, print output path when working with Linux or MacOS

3）removed file path in the test

**Comment by szabgab** [comment]
nice, but `data_sampling.py` still has path to file on your computer.

**Comment by DahaiSun** [comment]
Oh, sorry, I have updated it to the command way

The command is  ~python3 data_sampling.py <file_path> <sheet_name>
In my case : ~python3 data_sampling.py StatisticsQ1.xlsx Sheet1

**Comment by szabgab** [comment]
nice. I'd recommend you use backticks (the same button on the keyboard as the tilde ~) to mark `commands`.
