### ISSUE TITLE
Assignment day 6

### ISSUE THREAD

**Issue by AnitaMF** [szabgab/wis-python-course-2024-04#149]
https://github.com/AnitaMF/python_assignments/tree/main/Assignments/day_06

**Comment by szabgab** [comment]
In the programs (that you run) it would be better to move the code inside a function. (e.g. `main`)
Having a `global` variable is almost always a bad idea.
Testing should be done by `pytest`, creating a file that starts with `test_` and function(s) that has name starting with `test_` calling `assert`. the assert can be:

```python
assert all(0.9 <= row_sum <= 1 for row_sum in row_sums)
```

**Comment by AnitaMF** [comment]
Hi Garbor, 

I added the testing using pytest. 

thanks

**Comment by szabgab** [comment]
It still says that I need to use the `python` command to run the tests. That's not how it should be done. Please review how we wrote our tests and how we ran our tests. The test should not expect any input from the user.

**Comment by AnitaMF** [comment]
Hi Garbor, 

I fixed the test so it can actually work by only running "pytest" and also updated the readme file. 

Thanks

**Comment by szabgab** [comment]
It is really unclear to me what's going on here.
In the file `test_program.py` you "test" a function that is only available in the test file, right? What's the point?
there is also code `if __name__ ...` that will let you use the `test_program.py` as a command line program. what for? The test file should be only used by running `pytest`

The `count_to_frequencies.py` has no function and whatever it does is not tests.


It uses a file `frequency_functions.py` as a module, but that is not tested either and it has a `global` variable. You should never use `global` variables.

**Comment by AnitaMF** [comment]
Hi Garbor, 

I fixed the code so it won't include global variables. 
Regarding the pytest: 
I understand now my confusion, sorry.
My code takes a table with counts and calculates frequencies for each row. I wrote a new function, to check if the frequencies were calculated correctly for any file (sum of each row should be equal to 1) and not specifically for the file I am providing. 

I have now added a test_TNF.py file which check the results (and functioning of the functions), specifically for the example file I am providing.

**Comment by szabgab** [comment]
I guess this exception should not happen, right?


```
$ python check_results.py readCount_bacteria.csv 
Traceback (most recent call last):
  File "/home/gabor/Weizmann-2024-04/Ana-Meija-Fleisacher/Assignments/day_06/check_results.py", line 27, in <module>
    check_row_sums(filename)
  File "/home/gabor/Weizmann-2024-04/Ana-Meija-Fleisacher/Assignments/day_06/check_results.py", line 15, in check_row_sums
    assert all(0.9 <= row_sum <= 1 for row_sum in row_sums), "Calculation failed: Not all row sums are in the range of 0.9 to 1."
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Calculation failed: Not all row sums are in the range of 0.9 to 1.

```
