### ISSUE TITLE
Assignment 6 - Hernan Rubinstein :)

### ISSUE THREAD

**Issue by hernanRubinstein** [szabgab/wis-python-course-2024-04#150]
https://github.com/hernanRubinstein/Solutions_Python_BC/tree/main/Day06

**Comment by szabgab** [comment]
In the Markdown files (README.md) a `#` indicates title and `##` indicates subtitle. Did you want your lines to be all titles?

The `len` of `sys.argv` isn't checked in `assignment_d6.py` and so running `python assignment_d6.py` will show a nasty exception.

I don't see a test.

**Comment by hernanRubinstein** [comment]
Thank you,
Here I updated all issues you mentioned:
https://github.com/hernanRubinstein/Solutions_Python_BC/tree/main/Day06

**Comment by szabgab** [comment]
looks good
