### ISSUE TITLE
Assignment 6

### ISSUE THREAD

**Issue by liroh99** [szabgab/wis-python-course-2024-04#151]
Hi, here is a link to assignment 6. 
https://github.com/liroh99/Assignments/tree/main/day06

Have a great weekend!

**Comment by szabgab** [comment]
In the test there is no need to call the functions (no need for `test_calculate_gene_expression()`) as it is done by `pytest`. It can actually even hurt the testing.

In this case there is also no need to `import pytest`

Also please check the warning you get when you run `pytest`:

```
====================================================================================== warnings summary ======================================================================================
test_convert_data.py:10
  /home/gabor/Weizmann/Liron-Hoffman/day06/test_convert_data.py:10: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert(col, 0.00000049273705977)

test_convert_data.py:14
  /home/gabor/Weizmann/Liron-Hoffman/day06/test_convert_data.py:14: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert(col,0.000000274015319320)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================================================== 1 passed, 2 warnings in 0.56s ================================================================================
```

**Comment by liroh99** [comment]
For some reason it didn't show that error when I ran, perhaps I missed it. 
I believe it is now fixed. 
https://github.com/liroh99/Assignments/blob/main/day06/test_convert_data.py
Thank you!
