### ISSUE TITLE
🎉 Assignment day06 - Shaked Levy 

### ISSUE THREAD

**Issue by LevyShaked** [szabgab/wis-python-course-2024-04#153]
https://github.com/LevyShaked/Assignments_rep/tree/main/day06

**Comment by szabgab** [comment]
* there should be no code outside of functions as there is in `dimension_test.py`
* If I run `pytest` in the day06 folder  get this error:
* Do I see correctly that `test_day06/dimension_test.py` is an almost identical copy of `dimension_analysis.py` ? Do not copy your code and test the copy. Test the functions in the real code.
```
test_day06/dimension_test.py:27: in <module>
    file_reder("N_axis_test.csv",N_axis_vec)
test_day06/dimension_test.py:8: in file_reder
    with open(file) as csvfile :
E   FileNotFoundError: [Errno 2] No such file or directory: 'N_axis_test.csv'
```

**Comment by LevyShaked** [comment]
all fixed.
https://github.com/LevyShaked/Assignments_rep/tree/main/day06

**Comment by szabgab** [comment]
now it looks good.
