### ISSUE TITLE
Research proposal - Hadar

### ISSUE THREAD

**Issue by HadarKlimovski** [szabgab/wis-python-course-2024-04#154]
https://github.com/HadarKlimovski/proMALS_Prjoect

Im a rotation student in Hornstein lab, and i just started to working on a project, I will use the material we learned in the course to explore this data.

Hadar Klimovski

**Comment by szabgab** [comment]
Nice, but please also include the more technical part in the readme. How to install the dependencies, how to run the program, what kind of input the program expects. How to run the tests of the program.

**Comment by HadarKlimovski** [comment]
https://github.com/HadarKlimovski/proMALS_Prjoect

**Comment by szabgab** [comment]
looks good. Good luck
