### ISSUE TITLE
day06 Zhigileva Ekaterina

### ISSUE THREAD

**Issue by katyazhi** [szabgab/wis-python-course-2024-04#155]
Hello, here is my day06 homework:

https://github.com/katyazhi/solutions/tree/main/day06

**Comment by szabgab** [comment]
As you import the main program in the test it will also call `main()` during test which I think you did not want. Check what I said about `__name__`

**Comment by katyazhi** [comment]
Dear Gabor, 
I don't import the main program in test. My main program is in file called conductivity_calc.py and for test I import conductivity_fun.py file, which contains only functions. Is this possible that you accidentally confused names of files as they look similar?

**Comment by szabgab** [comment]
Indeed, likely that's what happened. I am sorry.

It looks good.
