### ISSUE TITLE
day6 - theam

### ISSUE THREAD

**Issue by theammn** [szabgab/wis-python-course-2024-04#161]
Hi, 

this is my assignment from a data I obtain after qPCR for target lines from my project in my lab!

best, 
thea

**Comment by szabgab** [comment]
no functions? no tests?

**Comment by theammn** [comment]
https://github.com/theammn/assignments/tree/main/day6
hi, updated version!

**Comment by szabgab** [comment]
There is no `.gitignore` file and thus `day6/__pycache__/functions.cpython-38.pyc` was added to the repository. Please remove that file and add the `.gitignore` to avoid adding these generated files.

The test files should start with `test_` to allow `pytest` to find them.

In the test files you do no need to call any of the test functions so the whole bottom section can be removed:

```
if __name__ == "__main__":
    test_calculate_real_change()
    test_calculate_fold_change()
    test_calculate_avg_fold_changes()
    print("All tests passed!")
```

**Comment by theammn** [comment]
done! thanks for your advices
