### ISSUE TITLE
Meir Sylman Project proposal

### ISSUE THREAD

**Issue by MeirSylman** [szabgab/wis-python-course-2024-04#169]
Project Proposal

I thought about a program for general biology-genetic processes. It teaches some basic and important skills and can also be used as a social activity.

https://github.com/MeirSylman/Project_from_Electropherogram_to_peptide/tree/main

**Comment by szabgab** [comment]
Nice proposal.
I'd get rid of the "project_" from the reponame.
Please also include the instructions how to install dependencies, how to run the tests and how to run the program. (See the other proposals)

**Comment by MeirSylman** [comment]
Fixed.

**Comment by szabgab** [comment]
nice. enjoy!
