### ISSUE TITLE
Project proposal - Yael Arieli

### ISSUE THREAD

**Issue by yaelarieli** [szabgab/wis-python-course-2024-04#173]
https://github.com/yaelarieli/Project---WIS-Python-course/tree/main

**Comment by szabgab** [comment]
Very nice. One thing: I'd name the repository according to what the project is and not that it is the wis course project. e.g. `adiabatic-fraction-in-a-cloud` After all this is expected to have value beyond the course. Please comment here the new address if you change the name of the repository.

**Comment by szabgab** [comment]
Oh and please also give a more descriptive title to the project that is meaningful to other researchers.
