### ISSUE TITLE
Project repository - Avital Rosner

### ISSUE THREAD

**Issue by Avitalrosner** [szabgab/wis-python-course-2024-04#178]
Hi,
Here is a link to my final project repository:

https://github.com/Avitalrosner/Project/tree/main

Thank you,
Avital

**Comment by szabgab** [comment]
Excellent.
One comment: please give this project a real name (and not "Project") something that other researchers will understand.  I'd recommend you also rename the repository accordingly. After all the project will have value beyond this course and beyond being the "project".
