### ISSUE TITLE
Project Proposal_Roi Siegelman

### ISSUE THREAD

**Issue by roisiegelman** [szabgab/wis-python-course-2024-04#192]
https://github.com/roisiegelman/Project

**Comment by szabgab** [comment]
looks good, but please rename the repository to reflect the title of the project and not "project".

**Comment by roisiegelman** [comment]
Done
https://github.com/roisiegelman/NSD1-in-Breast-Cancer

**Comment by szabgab** [comment]
nice. enjoy!
