### ISSUE TITLE
day06 Boaz Yaari

### ISSUE THREAD

**Issue by Boaz-Y** [szabgab/wis-python-course-2024-04#195]
Hi Gabor, I completed assignment06 and will continue to use this theme for the project (analyzing genomic data for arginine rich regions)

https://github.com/Boaz-Y/Solutions/tree/main/day06

Happy Shavuot,
Boaz

**Comment by szabgab** [comment]
We usually use uppercase letters for the `README.md` file. In the md file use backticks to mark code or commands, e.g. `.FASTA` makes it stand out nicely.

I get this error:

```
$ python shorten_proteome.py 
Traceback (most recent call last):
  File "/home/gabor/Weizmann-2024-04/Boaz-Yaari/day06/shorten_proteome.py", line 6, in <module>
    df = pd.read_csv(input_file)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/gabor/venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'proteome.csv'
```

The `fasta2csv.py` has a line: `fasta_file = "C:\work\Boaz-Y.github.io\day06\proteome.fasta"`  that makes the code unusable everywhere except your own compuer.

**Comment by Boaz-Y** [comment]
Hi Gabor, I corrected the readme file name, and changed it from a .txt file
to a .md markdown file.
Regarding the errors: I corrected the fasta2csv.py to use the file name.
This program, and the shorten_proteome.py program are explained in the
readme file, but in short, I included them even though they weren't exactly
the goal of the program. The .FASTA file needed to be converted to .CSV and
the complete proteome file was too large to be added to github, so I wrote
another program to shorten it. Since I can't add the whole proteome file, I
didn't add it to the github folder.
Thanks and have a great weekend,
Boaz

**Comment by szabgab** [comment]
A few comments:

* Why can't you add the whole proteome file?
* Without that I don't seem to be able to run any of the programs as they all rely on that.
* In the markdown files and also in the issue comments you can use backtick to emphasize filenames as I did above.
* Instead of including the fixed filenames in the program it would be much better if they accepted them on the command line. e.g.:

```
CountArgs.py proteome.csv analyzed_proteome.csv
```

That would make the programs more flexible to use.

**Comment by Boaz-Y** [comment]
Thanks for the input Gabor,
I'm not able to add files greater than 25MB. For this I had to make a
"shortened" proteome file that was under 25MB. This is what the program
`CountArgs.py` runs on. Would you like me to send the whole proteome file
(54MB) using another method?
I updated the programs so that they all accept the files in the terminal.
Thanks,
Boaz

**Comment by szabgab** [comment]
OK. So now I can run

```
python CountArgs.py shortened_proteome.csv out.csv
```

Ideally, you'd include this in the README so people who are not familiar with your project, that is everyone except of you., and maybe also you 3 months from now, will know how to use it.
