### ISSUE TITLE
Project Proposal - Omer Sapir

### ISSUE THREAD

**Issue by OmerSapir** [szabgab/wis-python-course-2024-04#197]
https://github.com/OmerSapir/Python-course-assignments/tree/main/Final_Project

**Comment by szabgab** [comment]
It looks good, but please move this to its own repository that has a repo-name reflecting the title of the project.

**Comment by OmerSapir** [comment]
https://github.com/OmerSapir/Analysis-Tool-For-UAV-Measurments

**Comment by szabgab** [comment]
nice, enjoy!
