### ISSUE TITLE
github Meir Sylman

### ISSUE THREAD

**Issue by MeirSylman** [szabgab/wis-python-course-2024-04#2]
https://meirsylman.github.io/

https://github.com/MeirSylman/MeirSylman.github.io

**Comment by szabgab** [comment]
I accept this, but please add more content.

**Comment by MeirSylman** [comment]
Hi,

I tried to add more text and a figure. In the editing page it looks good,
but from an external view the figure does not appear.
How can I  fix that problem?

Thank you,
Meir

‫בתאריך יום ה׳, 11 באפר׳ 2024 ב-12:55 מאת ‪Gábor Szabó‬‏ <‪
***@***.***‬‏>:‬

**Comment by szabgab** [comment]
Instead of

```
![strawberry](https://github.com/MeirSylman/MeirSylman.github.io/blob/main/WhatsApp%20Image%202024-04-14%20at%2011.23.55.jpeg)
```

Try

```
![strawberry](/WhatsApp%20Image%202024-04-14%20at%2011.23.55.jpeg)
```

**Comment by szabgab** [comment]
Though I think I'd start by renaming the image file so it won't contain spaces and then use that name.

**Comment by MeirSylman** [comment]
It worked the first way you wrote to me.

Thank you very much!

Meir

‫בתאריך יום א׳, 14 באפר׳ 2024 ב-11:51 מאת ‪Gábor Szabó‬‏ <‪
***@***.***‬‏>:‬
