### ISSUE TITLE
day07 - Shaked Levy

### ISSUE THREAD

**Issue by LevyShaked** [szabgab/wis-python-course-2024-04#201]
https://github.com/LevyShaked/Assignments_rep/tree/main/day07

**Comment by szabgab** [comment]
```
$ python ncbi.py a.txt cat 1
Usage: ncbi.py FileName Term Number
```

I am not sure what does it want from me. I provided all 3 parameters as it asked me.

**Comment by LevyShaked** [comment]
There is no need for "FileName", just as there is no need to do hw at 3 am 
fixed
https://github.com/LevyShaked/Assignments_rep/tree/main/day07

**Comment by szabgab** [comment]
ok
