### ISSUE TITLE
day08 assignment- Liron Hoffman

### ISSUE THREAD

**Issue by liroh99** [szabgab/wis-python-course-2024-04#207]
Hi, I am linking my solution to assignment 8. 
https://github.com/liroh99/Assignments/tree/main/day08

I also noticed even though I put in the gitignore the virtual environment, it was still found in my root, so I deleted it and created a new virtual environment and it seems now to work fine. Hopefully now I won't be spamming you. 

Shabbat Shalom, 
Liron

**Comment by szabgab** [comment]
Your virtual environment was in a folder called `env` while `.gitignore` has `venv` in it.
You should add `README.md` and `requirements.txt` to the day8 folder as well.

The solution is good.
