### ISSUE TITLE
Project Proposal - Noy Ravensary

### ISSUE THREAD

**Issue by NoyRavensary** [szabgab/wis-python-course-2024-04#209]
Hi,

This is my project proposal: a fun and educational protein quiz game that will help every player learn and enjoy.
https://github.com/NoyRavensary/Python-Course-Assignments/tree/main/Protein%20Quiz%20Game

thanks !

**Comment by szabgab** [comment]
Looks good, but this needs its own repository. probably called `protein-quiz-game`.

**Comment by NoyRavensary** [comment]
thanks !

created a new repo : 
https://github.com/NoyRavensary/Protein-quiz-game/tree/main

Noy.

**Comment by szabgab** [comment]
nice. Good luck!
