### ISSUE TITLE
project proposal Yuval Bernard

### ISSUE THREAD

**Issue by YuvalBernard** [szabgab/wis-python-course-2024-04#216]
https://github.com/YuvalBernard/Fitting-Z-spectra-via-Nonlinear-Least-Squares/tree/master

**Comment by szabgab** [comment]
looks good.

**Comment by YuvalBernard** [comment]
@szabgab  Hello Gabor, I'd like to consult with you.
To complete the final project I need to write tests.
The bulk of the code deals with providing a GUI front-end to the core operation: least squares fitting.
How do you advise to go about it? Is there a requirement to write tests for the GUI itself, or just for the core functionality? If so, how are tests written for tkinter applications?

Thanks

**Comment by szabgab** [comment]
Writing tests for a GUI is hard. I don't recommend it. I would only write automated tests for the code that does not need the GUI. In a bigger application the GUI should be a thin layer on top of the business logic
