### ISSUE TITLE
proposal - theam

### ISSUE THREAD

**Issue by theammn** [szabgab/wis-python-course-2024-04#222]
https://github.com/theammn/TDP43_project/tree/main

hi, this is the link to my proposal! if you need more information , i will add!

best, 
thea

**Comment by szabgab** [comment]
This is invisible for me. Is the address correct? Is it maybe a private repository?

**Comment by theammn** [comment]
it should be working now!

**Comment by szabgab** [comment]
I can see it now, but it seems to be missing the technical part, how to run run the program etc. Please take a look at the other projects.

**Comment by theammn** [comment]
oh for sure, i thought it was just the idea! i add a methodoly part to explain the different steps
