### ISSUE TITLE
proposal Boyue

### ISSUE THREAD

**Issue by DahaiSun** [szabgab/wis-python-course-2024-04#231]
https://github.com/DahaiSun/Mitochondrial_dispersal_statistics/tree/main

**Comment by szabgab** [comment]
nice, but  this still needs to have the specific instructions on how to install dependencies, run the tests and the application itself. Please see the other proposals.

**Comment by DahaiSun** [comment]
yes, I have updated the proposal

**Comment by szabgab** [comment]
ok. enjoy!
