### ISSUE TITLE
9 part 3  TIMESTAMP

### ISSUE THREAD

**Issue by HadarKlimovski** [szabgab/wis-python-course-2024-04#235]
00:00 :Introduction with sys library to access command-line arguments and the re library for regular expression operations.
7:00 : Uses a regular expression to check if the provided argument consists of one or more digits only.
10:18 : digit in a string
10:53 : exactly one character in a string in it is a digit
12:48: one or more digits in the string and nothing else
15:10 find unicode digit in arabic
18:42 : wikipedia 'numerals in unicode
19:10 : one or more unicode digit
20:00 input validation
22:00 : check if 2 character are the same 
26:17 : DNA with regex [1 or more characters]
33:00 : fined the longest sequence 
35:00 : Regex DNA web

**Comment by szabgab** [comment]
thanks
