### ISSUE TITLE
Adding Sameeha' page

### ISSUE THREAD

**Issue by Sameeham** [szabgab/wis-python-course-2024-04#24]
https://github.com/Sameeham/sameeham.github.io
https://sameeham.github.io/

**Comment by szabgab** [comment]
nice

**Comment by Sameeham** [comment]
Dear Gabor,
I hope you are doing well and had a great vacation,

I am facing a problem, that all the changes that I am doing I am not able to push them to my git hub.  [cid:9efa0661-6ffb-4262-9311-ef0710bfde4e]
Do you have any suggestion ? I have tried to solve it usining chatgpt but I could not

My kind regards
Sameeha
________________________________

**Comment by szabgab** [comment]
Either describe here what you are doing and what is the error message, or at the beginning of the next meeting ask me to help by looking at your desktop and fixing it together.

**Comment by Sameeham** [comment]
Dear Gabor,
Thank you for your reply;
We could discuss this; we could fix this together in our upcoming meeting,

Thank you in advanced
Sameeha
________________________________
