### ISSUE TITLE
Project - Yael Arieli

### ISSUE THREAD

**Issue by yaelarieli** [szabgab/wis-python-course-2024-04#254]
Hello, 
This is the link for my [project](https://github.com/yaelarieli/Project---WIS-Python-course/tree/main).

I sent it before to [Maher Salhab](https://mahers7.github.io/) for his review.

Thank you for the course!
Yael

**Comment by szabgab** [comment]
Thanks. Please rename the repository as I asked in #173.

**Comment by yaelarieli** [comment]
Ok, I renamed it.
[project](https://github.com/yaelarieli/Calculate-adiabatic-fraction-in-a-cloud)

**Comment by szabgab** [comment]
nice
