### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#255]
Hey,
sorry for the delay, I have just got the data for the project.
please see attached my project proposal - [https://github.com/AdiBarelMeisel/Gene-Amplification-and-SNP-Analysis](url)

I added snipped file of my data because the original file is 1 GB and was too large.
thank you,
Adi
@szabgab

**Comment by szabgab** [comment]
looks good. Go for it.
