### ISSUE TITLE
Final Project-Maher Salhab

### ISSUE THREAD

**Issue by Mahers7** [szabgab/wis-python-course-2024-04#266]
Hi, 
This is the link for my final project- https://github.com/Mahers7/FABP7_localization_motifs
The project reviewed by Yael Arieli

Thank you for the course.

**Comment by szabgab** [comment]
The requirements.txt should not include standard modules , remove these

```
-os
-csv
-tkinter
```

otherwise looks ok

**Comment by Mahers7** [comment]
Done.
