### ISSUE TITLE
Final project- Liron Hoffman

### ISSUE THREAD

**Issue by liroh99** [szabgab/wis-python-course-2024-04#267]
Hi, after back and forth with Hernan Rubenstein who is also in my lab, I have upgraded my code and fixed any bugs that have occurred. Other people in the lab have also given me their results and I verified it works properly. The next step is to add other statistical tests to the repository.
https://github.com/liroh99/qPCR_data_analysis
Thanks for the course, I learned a lot and it is nice to see my work have practical application. 

Liron :)

**Comment by szabgab** [comment]
nice
