### ISSUE TITLE
Project submission - Hernan Rubinstein

### ISSUE THREAD

**Issue by hernanRubinstein** [szabgab/wis-python-course-2024-04#268]
Hello,

After discussing with Chen Davidian Karisi, I have successfully upgraded my code and addressed all identified bugs. I've also received and validated results from other lab members, confirming their proper functionality. Our next step involves incorporating additional statistical tests into the repository.

You can access the updated code on [this GitHub repository](https://github.com/hernanRubinstein/Characterizing-Signaling-Dependent-Programs-During-Embryonic-Cell-fate-Decisions-in-vivo).

I am grateful for the course, which has provided valuable insights, and I am excited to see how our work contributes practically.

Best regards,
Hernan

**Comment by szabgab** [comment]
The requirement.txt had a lot of entries that should not be listed:

```
-mpl_toolkits
-subprocess
-tkinter 
-sklearn
-traceback
-argparse
```

One should not have code in the application that installs modules. That should be the responsibility of the person downloading your code.

Otherwise nice.
