### ISSUE TITLE
final project Hadar klimovski

### ISSUE THREAD

**Issue by HadarKlimovski** [szabgab/wis-python-course-2024-04#273]
https://github.com/HadarKlimovski/proMALS_Prjoect

Thank you very much for the course, it was very helpful. I really liked that you teach how to use of git, it's something I wanted to learn and I think it's very important.
also, before I did the course, my code was very messy, and since I learned to write functions the code looks better.
best, hadar

**Comment by szabgab** [comment]
```
$ pip install -r requirements.txt 
ERROR: Invalid requirement: 'conda-forge::scikit-learn' (from line 4 of requirements.txt)
```
after changing it to only `scikit-learn` and removing the `os` and `pickle` lines from requirements.txt  I could install the requrements.

`__pycache__/` is not in gitignore


running `pytest` fails with:

```
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_prepare_data_model.py:4: in <module>
    from cox import prepare_data_to_model
cox.py:31: in <module>
    from utils import load_raw_proteomics_data, rename_columns, drop_protein, describe_proteins_and_samples, norm_and_log,prepare_data_to_model,describe_clinical_data
E   ModuleNotFoundError: No module named 'utils'
```

**Comment by HadarKlimovski** [comment]
you right! one utils file is missing thank you, im sorry for that! i added it its work!

thank you

**Comment by szabgab** [comment]
thanks
