### ISSUE TITLE
Final Project Boaz Yaari

### ISSUE THREAD

**Issue by Boaz-Y** [szabgab/wis-python-course-2024-04#274]
Hi Gabor,
Here is the link for my final project:

https://github.com/Boaz-Y/Solutions/tree/main/project

Thank you for the course. I learned a lot of practical aspects of programing as opposed to theory. Additionally the project was something that I've wanted to analyze for a while and it really gave me the opportunity to run it. On the side I learned to run this on our cluster and troubleshoot many aspects I didn't think about before.

Boaz

**Comment by szabgab** [comment]
Please move the project to a separate repository that reflects the name of the project.

**Comment by Boaz-Y** [comment]
Sure thing.
It's available in the repository:
https://github.com/Boaz-Y/Codon_abundance_analyzer

**Comment by szabgab** [comment]
nice
