### ISSUE TITLE
Adi BarEl Meisel - Final Project

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#276]
Hi, 
Apologize for the delay, needed some focus from my PI and it took some time as well as the exams period.
Please see the final project repo here - [(https://github.com/AdiBarelMeisel/Gene-Amplification-and-SNP-Analysis)](https://github.com/AdiBarelMeisel/Gene-Amplification-and-SNP-Analysis).
Thank you for the course, it was very helpful! I really liked learning how to use git, I wanted to learn it for long time.

Thanks in advance!
Adi
@szabgab

**Comment by szabgab** [comment]
nice
