### ISSUE TITLE
Mazal Faraj - Final Project

### ISSUE THREAD

**Issue by Mazalik** [szabgab/wis-python-course-2024-04#277]
Hello, 

Please see the final project repo here - https://github.com/Mazalik/CefprozilGutImpact

Thank you for an useful and informative course! 
Mazal

**Comment by szabgab** [comment]
Running pytest I got this error: 

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\work\\python\\project/samples_loaded.txt'
```

**Comment by szabgab** [comment]
and I see this line in the code:

```
samples_loaded, superkingdom, species_abundance, project, families_table = fn.get_raw_data(["analyze_cefprozil_effect.py", "C:\\work\\python\\project"]) ####לעדכן####
````

**Comment by Mazalik** [comment]
Hi! 

Are you working on the latest version? 
it should be updated and the line should be: 

 #Getting the raw data and the project data
    samples_loaded, superkingdom, species_abundance, project,families_table = fn.get_raw_data(sys.argv)
    
 (without the "לעדכן" comment in it)

**Comment by szabgab** [comment]
I am working on the latest available on GitHub. The line is [there](https://github.com/search?q=repo%3AMazalik%2FCefprozilGutImpact%20%D7%9C%D7%A2%D7%93%D7%9B%D7%9F&type=code)

**Comment by szabgab** [comment]
I saw there was an update, so I also updated locally. Now `pytest` gives me this error

```
FAILED test_functions_analyze_cefprozil_effect.py::test_get_raw_data - FileNotFoundError: [Errno 2] No such file or directory: '/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/input_files/species_abundance.txt'
FAILED test_functions_analyze_cefprozil_effect.py::test_no_null_values - FileNotFoundError: [Errno 2] No such file or directory: '/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/input_files/species_abundance.txt'
FAILED test_functions_analyze_cefprozil_effect.py::test_data_types - FileNotFoundError: [Errno 2] No such file or directory: '/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/input_files/species_abundance.txt'
```

**Comment by Mazalik** [comment]
Ok i think i fixed it (i updated the code files and the README as well). 

Please notice that the **all the input files** should be in the "input_files" dir (including 2 csv files and the species_abundance.txt downloded from the link provided in the README file).

(since the species_abundance.txt file is very big, i couldn't upload it to the git repository). 

hope it will work correctly this time,

Thank you again!!

**Comment by szabgab** [comment]
You should probably have a shortened version of the species_abundance.txt for the tests so you can add them to the repo.
Otherwise people who download the code and run the tests will think the code is broken.

**Comment by Mazalik** [comment]
Thank you for the suggestion! I’m concerned that a shortened species_abundance.txt might confuse users and lead to incorrect results. Also, the filtering process is complex, and creating a valid short version before the filtering process is quite challenging. I’d prefer to avoid potential misunderstandings. Does that sound okay to you?

**Comment by szabgab** [comment]
Fine, but then those test should not run by default.

What you could do is to run tests conditionally using [skipif](https://slides.code-maven.com/python/pytest-skiping-test.html) and make them only run when the file exists.

You might also want to add this as an explanation to the [testing section of the readme](https://github.com/Mazalik/CefprozilGutImpact?tab=readme-ov-file#tests)

**Comment by szabgab** [comment]
I'd also add `input_files/species_abundance.txt` to the `.gitignore` file.

**Comment by szabgab** [comment]
running `python analyze_cefprozil_effect.py ` without any parameter gives me an exception:

```
Traceback (most recent call last):
  File "/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/analyze_cefprozil_effect.py", line 55, in <module>
    main()
  File "/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/analyze_cefprozil_effect.py", line 15, in main
    samples_loaded, superkingdom, species_abundance, project,families_table = fn.get_raw_data(sys.argv)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/functions_analyze_cefprozil_effect.py", line 12, in get_raw_data
    files_path = sys_argv[1]
                 ~~~~~~~~^^^
IndexError: list index out of range
```

That's not very user friendly. It should give me a user-friendly error message and a hint what should I do.

**Comment by szabgab** [comment]
I got a bunch of warnings:

```
$ python analyze_cefprozil_effect.py input_files/ output
/home/gabor/venv/lib/python3.12/site-packages/plotnine/ggplot.py:606: PlotnineWarning: Saving 15 x 10 in image.
/home/gabor/venv/lib/python3.12/site-packages/plotnine/ggplot.py:607: PlotnineWarning: Filename: output/relative_abundance_plot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/home/gabor/venv/lib/python3.12/site-packages/scipy/stats/_stats_py.py:6951: RuntimeWarning: invalid value encountered in scalar divide
/home/gabor/git/Weizmann-2024-04/Mazal-Faraj-project/functions_analyze_cefprozil_effect.py:206: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.
```

**Comment by Mazalik** [comment]
Thank you for all the detailed suggestions! 😊
I've gone through your comments and did my best to implement the changes in the code. 
I hope it's improved now.

**Comment by szabgab** [comment]
very nice
