### ISSUE TITLE
HW2 solution - Yuval Bernard

### ISSUE THREAD

**Issue by YuvalBernard** [szabgab/wis-python-course-2024-04#32]
[Link to solutions repository](https://github.com/YuvalBernard/weizmann-python-assignments/tree/master/day02).

**Comment by szabgab** [comment]
Good solution, but it would be better if `guess` was not initialized before the loop. Try to create another solution in a separate file, so this will remain as well where you don't have `guess` outside of the loop. We discussed exactly this in the lecture.

**Comment by YuvalBernard** [comment]
Fixed.

**Comment by szabgab** [comment]
nice
