### ISSUE TITLE
Thay Karmin -  solution repository:

### ISSUE THREAD

**Issue by THAYKARMIN** [szabgab/wis-python-course-2024-04#34]
This it my solution repository:
https://github.com/THAYKARMIN/assignments

**Comment by szabgab** [comment]
Thanks.
There are a number of issues:
* `guess = int(input("guess again: "))` is duplicated
* I don't think you need `if guess == number` do you?
* `count = count + 1`  could be written as `count += 1` It will be clearer

Please either fix this solution or create another file with the fixed code.

**Comment by THAYKARMIN** [comment]
Hi Gabor,

I fixed my solution but encountered a problem to push them... when I run git status I get this:

thay@h-MacBook-Air-sl-ty day02 % git status
On branch main
Your branch and 'origin/main' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

nothing to commit, working tree clean
thay@h-MacBook-Air-sl-ty day02 % git pull
Enter passphrase for key '/Users/thay/.ssh/id_ed25519': 
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

**Comment by szabgab** [comment]
I think you can solve it by first running `git config pull.rebase true` and then running `git pull` again.

**Comment by THAYKARMIN** [comment]
ok thanks, I fixed my solution

**Comment by szabgab** [comment]
looks good
