### ISSUE TITLE
Roi Assignment 2

### ISSUE THREAD

**Issue by roisiegelman** [szabgab/wis-python-course-2024-04#38]
https://github.com/roisiegelman/roisassignmets.github.io

**Comment by szabgab** [comment]
There are a few issues with this solution
* It is better not to have spaces (or other special characters) in the filename, `Guess_the_number.py` would be better (use `git mv` to rename the file.
* Variable names should have some meaning. `x`, `y` and `z` are not really good.
* In this case the variable `z` really should not be there. Solve it without that.

Please update your solution.

**Comment by szabgab** [comment]
Oh and there is really no reason to have the `github.io` added to the name of this repository. That's only important for the "pages"

**Comment by roisiegelman** [comment]
Hi,
I have edited my scrip.
 Also I've also added a link to my lab and to another student's webpage:
https://roisiegelman.github.io/

**Comment by szabgab** [comment]
nice. thank you.
