### ISSUE TITLE
Yael Arieli - hw2

### ISSUE THREAD

**Issue by yaelarieli** [szabgab/wis-python-course-2024-04#39]
https://github.com/yaelarieli/wis-python-course-hw.git

**Comment by szabgab** [comment]
nice, but there are a few issues:

* No need to call `int` on the value generated by `random`. It is already an `int`.
* `input` is called 3 times. It would be better to call only once.

Please either fix this code or add another file where these are fixed.

**Comment by yaelarieli** [comment]
Thanks! I changed the code.

**Comment by szabgab** [comment]
Great.
The improvement to `number_of_guess+= 1` is nice, but it would be better to leave a space on both sides of the `+=` operator and to only have this line once.

**Comment by yaelarieli** [comment]
I changed that also.

**Comment by szabgab** [comment]
looks good, thank you
