### ISSUE TITLE
Omer Sapir HW2 Solution

### ISSUE THREAD

**Issue by OmerSapir** [szabgab/wis-python-course-2024-04#41]
https://github.com/OmerSapir/Python-course-assignments/tree/main

**Comment by OmerSapir** [comment]
https://github.com/OmerSapir/OmerSapir.github.io

**Comment by szabgab** [comment]
The site looks nice, but the solution, though seems to be correct has some issues:


* The folder should be Day02 or day_02 but no spaces in the name
* The file itself should have an extension `.py` 
* It would be better to put spaces around all the operators so write `guess > number`
* The `tries += 1` is repeated 3 times. Should be only one place

Please fix those issues.

**Comment by OmerSapir** [comment]
I really don't understand how to work with github on my own computer. I
can't sync the repository with my computer, the explanation about how to
push changes was quite complicated and really specific. What I did, I
just opened a new repository manually on GitHub and copy-pasted my code
from vs code.  I would like to know if there is a more simple way to work
with git.

Omer

‫בתאריך יום ד׳, 24 באפר׳ 2024 ב-11:08 מאת ‪Gábor Szabó‬‏ <‪
***@***.***‬‏>:‬

**Comment by OmerSapir** [comment]
https://github.com/OmerSapir/Python-course-assignments

**Comment by OmerSapir** [comment]
https://github.com/OmerSapir/Python-course-assignments

**Comment by szabgab** [comment]
nice
