### ISSUE TITLE
Avital Rosner - second assignment

### ISSUE THREAD

**Issue by Avitalrosner** [szabgab/wis-python-course-2024-04#45]
Good evening,

1. Here is a link to the second assignment (of the guessing game) - 
https://github.com/Avitalrosner/Python-course---Assignments-/blob/Day2/num_guess_game.py

2. Here is a link to the main webpage with all the needed additions -
https://avitalrosner.github.io/

**Comment by szabgab** [comment]
The web site is nice, the assignment has issues.
* It is not critical, but it would be better to rename the repository (via settings) to remove the trailing dash `-`
* The file should have `.py` extension.
* There is no need to convert the `computer_num` to  `int` as it is already an integer
* `num_of_guess += 1` appears 3 time. Please change the code so we'll only have it once.

**Comment by Avitalrosner** [comment]
Good afternoon, 
I have corrected all the above.
Thank you and happy holidays  :)

**Comment by szabgab** [comment]
nice
