### ISSUE TITLE
Ana MF- 2nd assignment 

### ISSUE THREAD

**Issue by AnitaMF** [szabgab/wis-python-course-2024-04#46]
Hi :) 

- Here is a link to the repository where I will be publishing my solutions and class exercises -
https://github.com/AnitaMF/python_assignments.github.io
- The solution to assignment 2 (guess number)  can be found here: 
https://github.com/AnitaMF/python_assignments.github.io/blob/main/Assignments/day_02/guess_number.py

- Here is a link to my updated homepage -
https://anitamf.github.io/

**Comment by szabgab** [comment]
Nice,

One comment:
There is no need to end the `python_assignments.github.io` repository with `github.io`. That is only necessary for the web site. You can rename it in the "settings".
