### ISSUE TITLE
Boaz Yaari - HW2 solution

### ISSUE THREAD

**Issue by Boaz-Y** [szabgab/wis-python-course-2024-04#47]
Hello and happy passover!
I'm linking to my page with the required ammendments:
https://boaz-y.github.io/

And to my solutions repository with the homework:
https://github.com/Boaz-Y/Solutions
the assignment in particular is here: https://github.com/Boaz-Y/Solutions/blob/main/day02/guessing_game.py

see you next week,
Boaz

**Comment by szabgab** [comment]
nice update for the page.

About the code:
* Most of those comments seem to be unnecessary. If you feel **you** need them then keep them, but I think they just make it harder to read the code.
* You call the `input` function in 3 different places. It would be better to eliminate at least 1 of them, though ideally you'd only have one place of input.

**Comment by szabgab** [comment]
This is still waiting for a resolution

**Comment by szabgab** [comment]
you misunderstood. I was not waiting for you to close the issue. I was waiting for you to fix the code based on the comments and then comment here so I can grade it

**Comment by Boaz-Y** [comment]
I understand. I fixed the changes (I changed the comments after your initial issue, I only changed the input functions now because beforehand it had a different message if the guess was higher or lower).

**Comment by szabgab** [comment]
ok
