### ISSUE TITLE
HW - day02

### ISSUE THREAD

**Issue by Mazalik** [szabgab/wis-python-course-2024-04#48]
Hello,

Link to my solutions repository: https://github.com/Mazalik/python_course_sol/tree/main

thank you,
mazal

**Comment by szabgab** [comment]
Looks ok, but there are a few improvements:

* the second `elif` in your code could be an `else`, there is no need for that condition.
* after `break` we usually don't use `else` or `elif` as that is the end of the loop.

**Comment by Mazalik** [comment]
thank you! 

I fixed the 'elif', 
about the 2nd comment -  I'm not sure I understand how i can not use the 'else' after the 'break' (my loop will acure always without the break becuse it is 'while TRUE' )

**Comment by szabgab** [comment]
This is what I meant, but I see I was not clear:

```python
    if user_guess == number:
        print(f"Good guess!")
        break

    if user_guess < number:
        print(f"your guess is too small, try again")
    else:
        print(f"your guess is too big, try again")
```

**Comment by Mazalik** [comment]
Got it, thanks for the clarification

**Comment by szabgab** [comment]
You are welcome.

Oh, and there is no need for the leading `f` if there is no `{}` in the string.
