### ISSUE TITLE
HW - Day02

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#49]
[Day02](https://github.com/OmerZachar/projects/tree/main/Day02)

**Comment by szabgab** [comment]
It seems you copied the `_config.yml` file and the `README.md` from the other repository. There is no need for the former and the latter should describe what you have in this repo. Oh I see it is "generated from https://github.com/OmerZachar/omerzachar.github.io"

The solution seem to work, but it would be better to call `input` only once. Either update this solution or add another file with a version where you call `input` only once.

**Comment by OmerZachar** [comment]
Hi Gabor,
this is what you meant:
https://github.com/OmerZachar/projects/blob/main/Day02/HW2.1.py

**Comment by szabgab** [comment]
There are still 2 calls to `input`. In the class we discussed this issue.
