### ISSUE TITLE
Home work 2 Hernan Rubinstein

### ISSUE THREAD

**Issue by hernanRubinstein** [szabgab/wis-python-course-2024-04#56]
Heres a link to my solutions repository:
https://github.com/hernanRubinstein/Solutions_Python_BC/tree/main

**Comment by szabgab** [comment]
there seem to be a mixup in the variables.

**Comment by hernanRubinstein** [comment]
Thank you for pointing this out, this is the fixed version:
https://github.com/hernanRubinstein/Solutions_Python_BC/tree/main

**Comment by szabgab** [comment]
now it is ok.
