### ISSUE TITLE
day03 solution

### ISSUE THREAD

**Issue by yaelarieli** [szabgab/wis-python-course-2024-04#59]
https://github.com/yaelarieli/wis-python-course-hw/tree/main/day03

**Comment by szabgab** [comment]
I would not call the `guessing_game` in two different places. I think the code would be cleaner if after the `while` on line 51 you'd call `guessing_game` immediately and then used the value returned by it which probably should not be called `user_guess` but something like `shall_we_continue` and should be true or false.

I would not call an empty `input` on line 36.
