### ISSUE TITLE
day02 assignment 

### ISSUE THREAD

**Issue by LevyShaked** [szabgab/wis-python-course-2024-04#62]
https://github.com/LevyShaked/Assignments_rep

**Comment by szabgab** [comment]
day2: 
One-letter variables are quite meaningless and the `y_n` is also rather confusing. It is better to give the variable meaningful names so it will be easier to read and understand the code.

The code asked me "Press y if you want to start" so I pressed "n" and then it asked me again. How can I stop the game?

The clock and the scoring is a nice touch.

day3: why do you need 3 `while` loops? 2 should be enough

**Comment by LevyShaked** [comment]
Hi Gabor,

Day02: I changed the name of the variable 'y_n', and added n to end the game
https://github.com/LevyShaked/Assignments_rep/blob/main/day02/A1.py

Day03: Fixed all the problems I hope, and used only 1 'while'
https://github.com/LevyShaked/Assignments_rep/blob/main/day03/A2.py

Thank you for the corrections, i learn from it 

Shaked

**Comment by szabgab** [comment]
> Thank you for the corrections, i learn from it

That's the idea :smile:
