### ISSUE TITLE
Day03 Solution

### ISSUE THREAD

**Issue by OmerSapir** [szabgab/wis-python-course-2024-04#63]
https://github.com/OmerSapir/Python-course-assignments/tree/main/Day03

**Comment by szabgab** [comment]
This code does not do anything - main is never called

 Very interesting approach, but I would not use the type of the variable as an indicator. I would first deal with all the input letters and only then would convert the input to an int.

**Comment by OmerSapir** [comment]
Can you explain?
When i call 'main()' it is working for me

**Comment by OmerSapir** [comment]
Just need to add 'main()' at the end of the code?

**Comment by szabgab** [comment]
> Just need to add 'main()' at the end of the code?

yes
