### ISSUE TITLE
Day03

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#64]
Hi Gabor, I have no previous background in coding and I honestly don't understand how to approach the exercise. I saw some of the students solutions and don't understand how to build this code after hearing the the recording of the lessons.

**Comment by szabgab** [comment]
A couple of suggestions

You might want to watch (also) the videos from [this recording](https://code-maven.com/programming-bootcamp-for-scientists) where I took another approach in teaching it. You can also do the assignments there which are more or less all the [exercises you can find in the slides](https://code-maven.com/slides/python/toc)

the general idea is to try to break down the problem into small steps you understand.

**Comment by OmerZachar** [comment]
https://github.com/OmerZachar/projects/tree/main/Day03

**Comment by szabgab** [comment]
There is  now a file `Day02/.DS_Store`, please remove it and add a `.gitignore` file as explained in the video to avoid adding it again.

We usually put the `import` statements at the top of the file before any function definition.

It is not a good idea to call the `main` function recursively again from inside the `main` function or from any other function. 

I don't see the value of returning "exit", "show" etc. words from `play_game`. It might have been better to split the `play_game` to a function checking the letters and a function checking the numbers, but if you are returning something you could keep the letters the user typed in.
