### ISSUE TITLE
Day02 - assignment 2

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#67]
https://github.com/AdiBarelMeisel/AdiBarelMeisel.github.io/blob/main/Assignments/Day02/assignment_2.py

**Comment by szabgab** [comment]
The assignments should be in a separate repository, not the one used for the web site. Please, move them and comment here with the new place

**Comment by AdiBarelMeisel** [comment]
Hey, I changed it. and also updated assignment number 03.
Please see attached assignment number 2.
[https://github.com/AdiBarelMeisel/Assignments/blob/main/Day02/assignment_2.py](url)

Thanks,
Adi

@szabgab

**Comment by szabgab** [comment]
Day 02 code now contains

```
<<<<<<< HEAD
print (f"You needed {times} to win the game.")
=======
print (f"You needed {times} to win the game.")
>>>>>>> cf0cd81f07580a6e782b71c22985a23f5ecddaf8
```

that was caused by git. You need to clean that up manually for this code to work.
