### ISSUE TITLE
day03

### ISSUE THREAD

**Issue by Mazalik** [szabgab/wis-python-course-2024-04#68]
https://github.com/Mazalik/python_course_sol/blob/main/day03/day03_number_guessing_game.py 

thank you :)

**Comment by szabgab** [comment]
* We usually put the import statements at the top of the file before any functions
* It is not a good idea to call `main` inside the functions this will create an deep recursion: better to have two while loops on in the other.
* It would be better to first check the input letters (x, n, s) and only then try to check for the input being numeric
* There should be only one place where you are asking for a guess, now there are 2

**Comment by Mazalik** [comment]
Hi,

Thank you!
I tried to change the code so that it will match your comments.
The new version is here:

https://github.com/Mazalik/python_course_sol/blob/main/day03/day03_number_guessing_game_improved.py

I didn't completely understand your fourth suggestion, but maybe in the new version it is better?

@szabgab
