### ISSUE TITLE
Shahar Garin - Assignment 3

### ISSUE THREAD

**Issue by ShaharGarin** [szabgab/wis-python-course-2024-04#70]
Hello.

I've completed day03 assignment. It can be found in [my HW repository](https://github.com/ShaharGarin/shahar_assignments).

**Comment by szabgab** [comment]
* It is not a good idea for a function to return "either string or bool" as `check_num` does. You might better off returning -1,  0, 1 in the 3 cases.
* The main function seems to be too long. I'd split that up.
