### ISSUE TITLE
Assignment day03 - Chen Davidyan Krisi

### ISSUE THREAD

**Issue by ChenDavidyan** [szabgab/wis-python-course-2024-04#74]
https://github.com/ChenDavidyan/Python_assignments/tree/main/day03

**Comment by szabgab** [comment]
Thanks.
It is not a good idea to call `main` more than once, that will create a deep recursion.
Try an approach where you have one `while` loop inside another `while` loop.

**Comment by ChenDavidyan** [comment]
Thanks, here's the modified code - https://github.com/ChenDavidyan/Python_assignments/blob/main/day03/guess_game_day03.py
