### ISSUE TITLE
Day3-Boyue Sun

### ISSUE THREAD

**Issue by DahaiSun** [szabgab/wis-python-course-2024-04#75]
Day3 Boyue Sun
https://github.com/DahaiSun/wis_python_course_assignments/tree/main/day3

**Comment by szabgab** [comment]
part of the assignment was to split up the code into several functions.

**Comment by DahaiSun** [comment]
> part of the assignment was to split up the code into several functions.

Hi Gabor, I have added another file with small functions
https://github.com/DahaiSun/wis_python_course_assignments/blob/main/day3/day03%20split%20to%20small%20functions.py

**Comment by szabgab** [comment]
Please use filename **without** spaces. (Use underscore between words in the filename)
