### ISSUE TITLE
Timestamps for Day 02 recording 03

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#77]
Hi Gabor,

I updated the timestamps for Day03 recording #03.
I wanted to ask if you have any recommendations for a good website for exercising pyhton?

Omer

**Comment by szabgab** [comment]
What do you mean you updated the timestamps of Day3 video 3 ? I saw this #76 and that's not you.

Try the exercises in my [slides](https://code-maven.com/slides/python/toc) and the Python track of [Exercism](https://exercism.org/) There is also [LeetCode](https://leetcode.com/) I have not tried.

**Comment by OmerZachar** [comment]
Hi, I updated the timestamp for the video of Day 02 recording 3.  sorry for the mixup!
I saw it on the pull request after the update.

**Comment by szabgab** [comment]
I am not sure which pull-request are you talking about and I can't seem to find those timestamps. Could you link to them, please?

**Comment by OmerZachar** [comment]
* 00:00 -  `git mv`
* 06:28 -  `if` condition and `else`
* 08:33 - Check for equality `==`
* 09:28 - indentation
* 18:30 - 'lower()'
* 21:54 - `capitalize`
* 24:30 - built-in method,  parentheses `()`
* 29:57 - `while`
* 34:05 - `break`
* 34:40 - `Ctrl-C`
* 35:28 - How to avoid the `break` (actualy the earlier solution using `break` is better)
* 41:15 - DRY
* 45:00 - random
* 45:50 - docs.python.org
* 50:30 - `random.random`  `random.randrange`
* 56:40 why did you use `git mv` ?

**Comment by szabgab** [comment]
ok, now I can see it.
