### ISSUE TITLE
day03 

### ISSUE THREAD

**Issue by Mazalik** [szabgab/wis-python-course-2024-04#78]
Hi,

Thank you!
I tried to change the code so that it will match your comments.
The new version is here:

https://github.com/Mazalik/python_course_sol/blob/main/day03/day03_number_guessing_game_improved.py

I didn't completely understand your fourth suggestion, but maybe in the new version it is better?

_Originally posted by @Mazalik in https://github.com/szabgab/wis-python-course-2024-04/issues/68#issuecomment-2098251947_

**Comment by szabgab** [comment]
yes, it is better.
