### ISSUE TITLE
assignment_day3- AnaMF

### ISSUE THREAD

**Issue by AnitaMF** [szabgab/wis-python-course-2024-04#79]
Hi Gabo, 

- This is the [link](https://github.com/AnitaMF/python_assignments/tree/main/Assignments/day_03) to the solution of assignment_3 
- I have added a list of nature places to visit to my [website](https://anitamf.github.io/) as requested & deleted the __pychache__ file 
Thanks

**Comment by szabgab** [comment]
very nice

**Comment by szabgab** [comment]
It is GaboR :smiling_face_with_tear:

**Comment by AnitaMF** [comment]
Ups, sorry!
