### ISSUE TITLE
Solution Day03 Hernan

### ISSUE THREAD

**Issue by hernanRubinstein** [szabgab/wis-python-course-2024-04#82]
Hi, here is my solution for day 03 exercise:
https://github.com/hernanRubinstein/Solutions_Python_BC/blob/main/Day03/Improved_guessing_game.py

Best regards,
Hernan

**Comment by szabgab** [comment]
* Using a strings e.g. "Restarting" or "Exiting Game" in 4 different places is error prone as there might be a typo in one place or if you need to change the text you have to remember to update it everywhere. It would be better to create a (constant) variable at the top of to file, e.g. `RESTARTING = "Restarting"`  and then use the variable name `RESTARTING` in all those places.

* input1 and input2 don't mean much (the numbering), it might be better to give a more meaningful name.

**Comment by hernanRubinstein** [comment]
Oh, I see, thank you very much for this tips,
Best,
Hernan


________________________________________________

Hernan Rubinstein | PhD student | +972 54 544 0942

Department of Molecular Cell Biology

Wolfson Building, Room 102-104

234 Herzl Street, Rehovot, 7610001 Israel


[cid:b98f563a-0741-46c7-9ab2-37977cef3cf3]
________________________________
