### ISSUE TITLE
soulotion 3

### ISSUE THREAD

**Issue by THAYKARMIN** [szabgab/wis-python-course-2024-04#85]
Hi Gabor,

Im not sure if we were supposed to open an issue for the solution but I uploaded it on Friday I think and got no feedback so I'm opening an issue now.

https://github.com/THAYKARMIN/assignments/tree/main/day03

Thay Karmin

**Comment by szabgab** [comment]
* The guess_game function is too long. you could split it into "dealing with the letters" and "dealing with the number" part
