### ISSUE TITLE
New github repository and website

### ISSUE THREAD

**Issue by YuvalBernard** [szabgab/wis-python-course-2024-04#9]
https://github.com/YuvalBernard/python-course-2024
https://yuvalbernard.github.io/python-course-2024/

**Comment by szabgab** [comment]
Please rename the tepo to yuvalbernard.github.io so it will be hosted at https://yuvalbernard.github.io/ and comment here when done.
And please, replace the Lorem Ipsum with some real content.

**Comment by YuvalBernard** [comment]
Thanks. Done.

**Comment by szabgab** [comment]
nice
