### ISSUE TITLE
Timelapse of Day4 part 3:

### ISSUE THREAD

**Issue by Avitalrosner** [szabgab/wis-python-course-2024-04#92]
Hi, here is the timelapse of Day4 part 3:

2:00 Example of counting characters.
4:00 Explaining "dictionary" - keys and values.
14:00 Changing the display of the output <>
20:00 Modifying the code, to read the file line by line.
28:00 Answering questions.
30:00 Jupyter notebook.
34:00 Debugger.

@szabgab

**Comment by szabgab** [comment]
Thanks, but this was already done in #3 by @katyazhi  Don't you coordinate who is doing which video in the WhatsApp group?

**Comment by Avitalrosner** [comment]
Hi,
I see now she did it on may 10th, which is strange since I wrote on may 9th on the WhatsApp group that I will do it.
Perhaps not all students are in that group?

**Comment by szabgab** [comment]
I don't know. I sent the invitation to everyone, but I am not in the group. I'll mark you as well as a person who had made timestamps.

**Comment by Avitalrosner** [comment]
Thank you, I appreciate it!
