### ISSUE TITLE
Day03 - Adi Bar-El Meisel

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#94]
Hey,

As you requested, I opened a new repo for all of the assignments.
Please see attached assignment number 03.
[https://github.com/AdiBarelMeisel/Assignments/blob/main/Day03/assignment_3.py3](url)

Thanks in advance,
Adi

@szabgab

**Comment by szabgab** [comment]
Day 02 code now contains
```
<<<<<<< HEAD
print (f"You needed {times} to win the game.")
=======
print (f"You needed {times} to win the game.")
>>>>>>> cf0cd81f07580a6e782b71c22985a23f5ecddaf8
```

that was caused by git. You need to clean that up manually for this code to work.

Day 03 looks good.

**Comment by AdiBarelMeisel** [comment]
fixed it  :)
@szabgab

**Comment by szabgab** [comment]
nice
