### ISSUE TITLE
Day4 assignment - Avital

### ISSUE THREAD

**Issue by Avitalrosner** [szabgab/wis-python-course-2024-04#96]
Hi, 
Here is a link to my 4th assignment:
https://github.com/Avitalrosner/Python_course_Assignments/tree/main/Day4

I've also made the time-lapse for day 4 part 3.

Thank you,
Avital

**Comment by szabgab** [comment]
I get a syntax error:

```
  File "/home/gabor/Weizmann/Avital-Rosner/Day4/counting.py", line 17
    text = file.read()
    ^
IndentationError: expected an indented block after 'with' statement on line 16
```

**Comment by Avitalrosner** [comment]
Thank you, I have fixed the issue. should be fine now :)

**Comment by szabgab** [comment]
ok, so this works now, but reading the content of the file 3 times is a bit waste of time. It is rather slow. It would be better to read it once and use the content in all 3 cases.
