### ISSUE TITLE
Day04 homework

### ISSUE THREAD

**Issue by OmerZachar** [szabgab/wis-python-course-2024-04#98]
https://github.com/OmerZachar/projects/tree/main/Day04

**Comment by szabgab** [comment]
naming the file "import sys.py" is a bad idea. very confusing. Please change.

**Comment by OmerZachar** [comment]
Hi Gabor, I have updated the file name to "file_object_count.py". You can check again with the previous link.

**Comment by szabgab** [comment]
looks good.

if you read the whole content of the file into memory using `read` then you can outdent the rest of the code:

```
with open(filename, 'r') as file:
    content = file.read()
char_count = len(content)
line_count = content.count('\n') + 1  
word_count = len(content.split())

print(f"Number of characters: {char_count}")
print(f"Number of lines: {line_count}")
print(f"Number of words: {word_count}")
```
